version: '3'

services:
  jupyter-ml-documentos:
    image: quay.io/jupyter/scipy-notebook:2024-03-14
    container_name: jupyter-ml-documentos
    ports:
      - 8888:8888
    volumes:
       - .:/home/jovyan
    environment:
      - .env
    command: >
      /bin/bash -c "
      jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root
      "
